platform :ios, '8.0'

target 'ShoppingCartDemo' do

pod 'ReactiveCocoa', '~> 2.5'
pod 'HandyFrame', :git => 'https://github.com/casatwy/HandyAutoLayout.git', :tag => '1.1.1'
pod 'SDWebImage'
pod 'MJRefresh'

end
